export const CARD = [
	{
		id: 1,
		title: 'Яблочный пирог',
		img: '/card/card-preview.jpg',
		tag: 'Новинка',
		rating: 4,
		cookingTime: 50,
		productInfo: {
			category: 'Выпечка',
			cuisine: 'Общая',
			season: 'Все сезонный',
		},
		originalPrice: 0,
		discountPrice: 0,
	},
	{
		id: 2,
		title: 'Изысканные кольца кальмаров с острым айоли и салатом',
		img: '/card/card-preview.jpg',
		tag: 'Новинка',
		rating: 5,
		cookingTime: 80,
		productInfo: {
			category: 'Закуска',
			cuisine: 'Азиатская',
			season: 'Все сезонный',
		},
		originalPrice: 500,
		discountPrice: 350,
	},
	{
		id: 3,
		title: 'Изысканные кольца кальмаров с острым айоли и салатом',
		img: '/card/card-preview.jpg',
		tag: 'Топ',
		rating: 3,
		cookingTime: 30,
		productInfo: {
			category: 'Закуска',
			cuisine: 'Азиатская',
			season: 'Весеннее блюдо',
		},
		originalPrice: 0,
		discountPrice: 0,
	},
	{
		id: 4,
		title: 'Изысканные кольца кальмаров с острым айоли и салатом',
		img: '/card/card-preview.jpg',
		tag: 'Новинка',
		rating: 3,
		cookingTime: 15,
		productInfo: {
			category: 'Закуска',
			cuisine: 'Азиатская',
			season: 'Осеннее блюдо',
		},
		originalPrice: 150,
		discountPrice: 150,
	},
	{
		id: 5,
		title: 'Изысканные кольца кальмаров с острым айоли и салатом',
		img: '/card/card-preview.jpg',
		tag: 'Новинка',
		rating: 3,
		cookingTime: 15,
		productInfo: {
			category: 'Закуска',
			cuisine: 'Азиатская',
			season: 'Осеннее блюдо',
		},
		originalPrice: 0,
		discountPrice: 0,
	},

	{
		id: 6,
		title: 'Изысканные кольца кальмаров с острым айоли и салатом',
		img: '/card/card-preview.jpg',
		tag: 'Новинка',
		rating: 3,
		cookingTime: 15,
		productInfo: {
			category: 'Закуска',
			cuisine: 'Азиатская',
			season: 'Осеннее блюдо',
		},
		originalPrice: 0,
		discountPrice: 0,
	},
]
